
version: "3"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: hotel
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
  api:
    build: .
    ports:
     - 3000:3000

volumes:
  postgres: