
version: "3"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: hotel
      POSTGRES_PASSWORD: hotel
      POSTGRES_USER: hotel
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - node-network
  api:
    build: .
    command:
      - npm
      - run
      - migration
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - node-network

volumes:
  postgres:

networks:
  node-network:
    driver: bridge